#!/bin/sh
# Configuration for N1GE Grid Engine
#$ -S /bin/sh
#$ -N SB2_0205
#$ -q highmem.q
#$ -p None
#$ -sync n
#$ -M pande.erawijantari@utu.fi
#$ -m abe
#$ -o /homes/perawija/data_pande/DREAM/FINRISK2022/post_challenge/FinriskHF_post1/TEAMS/SB2/SB2_0205.OU
#$ -e /homes/perawija/data_pande/DREAM/FINRISK2022/post_challenge/FinriskHF_post1/TEAMS/SB2/SB2_0205.ER
#$ -V 
#$ -cwd
cd /homes/perawija/data_pande/DREAM/FINRISK2022/post_challenge/FinriskHF_post1/TEAMS/SB2
# Increase stack
export MPSTKZ=8M
# Command to run
singularity run --net --network none /homes/perawija/data_pande/DREAM/FINRISK2022/post_challenge/FinriskHF_post1/TEAMS/SB2/sim_image/SB2_refining_v1.sif /homes/perawija/data_pande/DREAM/FINRISK2022/post_challenge/FinriskHF_post1 input_real scoring
